appName: helm-app
replicaCount: 1
replicas: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: latest

port: 80
configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: "This app was deployed with helm!"
