appName: Argo
replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: latest
  name: my-deployment

port: 80
configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: "This app was deployed with helm!"
